"use strict";
exports.__esModule = true;
var index_1 = require("../src/index");
console.log(new index_1["default"]().addDays(1));
console.log(new index_1["default"]().diffDays(new index_1["default"](2020, 2, 10)));
console.log(new index_1["default"]().dayOfYear());
console.log(new index_1["default"]().getTime());
console.log(new index_1["default"](1583035200000).toString());
console.log(new index_1["default"]().dayOfYear());
console.log(new index_1["default"]().getMilliseconds());
var dt = new index_1["default"]();
console.log(dt.toString('yyyy-MM-dd hh:mm:ss.fff'));
var dt1 = dt.addMilliseconds(123);
var dt2 = new index_1["default"]();
console.log(dt1.toString('yyyy-MM-dd hh:mm:ss.ff'));
console.log(dt1.compareTo(dt2));
console.log(new index_1["default"]('2020-03-03').addDays(-1));
console.log(new index_1["default"]('2020-03-03').getTime() / 1000);
console.log(new index_1["default"](2020, 4, 1).toString());
console.log(new index_1["default"](2020, 4, 1).addDays(-1).toString());
console.log(new index_1["default"](2020, 4, 1).addDays(-2).toString());
console.log(new index_1["default"](2020, 2, 29).addDays(-1).toString());
console.log(new index_1["default"](2020, 3, 1, 0, 15, 0).addDays(10).toString('yyyy-MM-dd hh:mm:ss.fff'));
console.log(new index_1["default"](2020, 3, 1, 0, 0, 0).addHours(-1).toString('yyyy-MM-dd hh:mm:ss.fff'));
console.log(new index_1["default"](2020, 3, 31).addMonths(-1).toString('yyyy-MM-dd hh:mm:ss.yyy'));
console.log(new index_1["default"]().addYears(4).toString());
console.log(new index_1["default"]().addMonths(-1).toString('yyyy-MM-dd hh:mm:ss.fff'));
console.log(new index_1["default"]().addMonths(1).toString('yyyy-MM-dd hh:mm:ss.fff'));
console.log(new index_1["default"]().isLeapYear());
console.log(new index_1["default"]().addYears(1).isLeapYear());
console.log(new index_1["default"]().addYears(1).toString('yyyy-MM-dd hh:mm:ss.fff'));
console.log(new index_1["default"](2020, 2, 29).addYears(1).toString());
console.log(new index_1["default"](2020, 12, 31).addMonths(-1).toString());
console.log(new index_1["default"](2020, 8, 31).addMonths(1).toString());
console.log(new index_1["default"](2020, 8, 31).addMonths(6).toString());
console.log(new index_1["default"](2020, 3, 31).addMonths(-1).toString());
console.log(new index_1["default"](2020, 1, 31).addMonths(1).toString());
console.log(new index_1["default"](2020, 6, 30).addMonths(1).toString());
console.log(new index_1["default"](2020, 6, 30).addMonths(-4).toString());
console.log(new index_1["default"](2020, 6, 30).addYears(1).addMonths(-4).toString());
